### ISSUE TITLE
encoding scheme which is either ObjectWithSingleField or bare string for nullary constructors

### ISSUE THREAD

**Issue by radix** [bartavelle/json-helpers#4]
feature request, feel free to close if you're not interested :)

If I have a sum type like

```
data Foo
  = Nah
  | Something Int
```

then I can't use ObjectWithSingleField, because it doesn't handle nullary constructors. I have a server which serializes such types as either `"Nah"` or `{"Something": N}` (where N is an int). It'd be nice if there were a convenience function which would work with these situations.

**Comment by radix** [comment]
I wrote up a little convenience:

```elm
sumDecoder name nullaryList singleFieldList = JD.oneOf
  [ JH.decodeSumUnaries name
      (Dict.fromList nullaryList)
  , JH.decodeSumObjectWithSingleField name
      (Dict.fromList singleFieldList)
  ]
```


(by the way, `decodeSumUnaries` is misnamed, unary constructors are constructors that take one argument, nullary constructors take none... just a note :)

**Comment by bartavelle** [comment]
You are very right for the function name. I just checked, and it was me misreading *nullary* in `aeson` :/

The design is based on Haskell's `aeson`, because I wrote this package to work with the `elm-bridge` package, and that's the reason for this limitation.

Would your issue be resolved if I basically rewrote your convenience function and incorporated it in the package?

**Comment by bartavelle** [comment]
Is that even possible to mark a function as deprecated in Elm?

**Comment by radix** [comment]
@bartavelle sure, consider my function contributed with all appropriate license :) I'm happily using the function for many data structures in my current project.

I'm not sure about the deprecation thing. I don't think there is a mechanism.

**Comment by bartavelle** [comment]
v1.3.0 is published, thanks again
