### ISSUE TITLE
Migrating to 0.19?

### ISSUE THREAD

**Issue by tmbull** [bartavelle/json-helpers#5]
Hi, I was wondering if you have plans to upgrade this package to elm 0.19? Since they've done away with custom infix operators, `>>=` and `:=` would need replaced. What are your thoughts? I'm currently using this library in conjuction with `elm-bridge` which will also need to be updated to generate 0.19 compatible output.

**Comment by bartavelle** [comment]
I will not use 0.19, so I do not really know.

I think the best thing to do would be to start with an update for 0.18 that drops all operators, and release elm-bridge in sync.

Did they change the json part? If not that would be sufficient.

**Comment by tmbull** [comment]
`Json.Encode` and `Json.Decode` were moved to [elm/json](https://package.elm-lang.org/packages/elm/json/latest), but I do not think that there were any other changes.

**Comment by bartavelle** [comment]
If you were kind enough to provide a PR that drops the operators and updates the version bounds, working with Elm 0.19, that would be awesome. I would then update `elm-bridge` to drop the use of operators.

**Comment by jerith666** [comment]
started hacking on this a bit at https://github.com/jerith666/json-helpers/tree/elm-019

**Comment by tmbull** [comment]
@jerith666, thanks for picking this up. I actually spent some time yesterday working on this as well, but it looks like you're further along than I got. I removed the infix operators, and got the tests passing again on 0.18, but started running into problems with converting it to 0.19. I wasn't sure what to do about the `toString` in `encodeMap`, but writing it in terms of `Json.Encode.dict` is a better approach anyway.

**Comment by jerith666** [comment]
just pushed some more commits ... the `:=` and `>>=` operators in the test code are annoying, not sure my global search-n-replace on them is correct.

**Comment by jerith666** [comment]
and ... are you saying that the tests are not currently passing at `master` (f391ce7)?

**Comment by tmbull** [comment]
@jerith666, no the tests on master are passing. What I meant was that I made the tests pass again after removing all of the infix operators. FWIW, I pulled down your branch and applied the fixes I had made. You can see my work here: https://github.com/tmbull/json-helpers/tree/elm-019

I didn't redefine the version of `andThen` with the parameters flipped like you did though, and it looks like you've already updated the test so I'm not sure if you will want to take my changes or not.

**Comment by jerith666** [comment]
I took your changes, thanks!

I can't actually run `elm-test` locally [1], but if you or @bartavelle could confirm the tests pass, I think we're ready to merge!  :)

[1] because https://github.com/stoeffel/elmi-to-json hasn't been added to https://github.com/NixOS/nixpkgs/ yet

**Comment by tmbull** [comment]
@jerith666 I pulled down your `elm-019-v2` branch and verified that the tests pass locally: 

```
$  elm-test
Success! Compiled 2 modules.
Success! Compiled 1 module.

elm-test 0.19.0-beta8
---------------------

Running 1012 tests. To reproduce these results, run: elm-test --fuzz 100 --seed 392614399828987


TEST RUN PASSED

Duration: 821 ms
Passed:   1012
Failed:   0
```
So I do think that we are ready to merge! Thanks again for working on this.

**Comment by bartavelle** [comment]
Yeah, thanks a *lot*!

**Comment by bartavelle** [comment]
```
Verifying bartavelle/json-helpers 1.5.0 ...

  ✗ Problem with your README.md
```

v0.19 is *intense*.

**Comment by bartavelle** [comment]
Also it seems that a package is either 0.18 or 0.19. Man, this will be *annoying* to test.

**Comment by tmbull** [comment]
Yeah... Elm 0.19 replaced `elm-package.json` with `elm.json`, so I had some initial hope that you could have a project that would build against both with different dependencies for each. Unfortunately, it seems that there were too many breaking code changes to make this realistic.

**Comment by bartavelle** [comment]
Yeah, but I have a plan! Changing `json-helpers` a bit and moving a lot of functionality to `elm-decode-pipeline`!

**Comment by bartavelle** [comment]
Soooooo, I stole a few things from noredink, and I have the end to end test compiling in `elm-bridge`.

Now I'll have to fix the tests and verify everything still works :(

**Comment by tmbull** [comment]
Thanks for jumping on the `elm-bridge` migration so quick.  Hopefully fixing the tests aren't too bad, but I know that migrating the `json-helpers` tests was a bit of a pain due to the infix operators. I do think that leaning on `elm-decode-pipeline` is a good idea, as it is a well maintained library that seems to be widely used in the community.

**Comment by bartavelle** [comment]
Unfortunately, it would require a lot more helpers to just lean on it, so I just stole some operators from them.

Before I fix the tests, can anyone check if the current state of json-helpers + elm-bridge produce good code for her/him or if it is complete bullshit?

**Comment by tmbull** [comment]
I can pull your elm-bridge changes down and test them in about an hour or so.

**Comment by tmbull** [comment]
Sorry, it took me a little longer than I expected to get back to this. I've built the tests. It's a bit hard to say if the output is correct or not since I can't compile it without a published `json-helpers` package for 0.19. I did notice one thing straight away:

For tuple decoders, you are generating something like this:

 `required "tuple" (Json.Decode.map2 (,) (Json.Decode.index 0 (Json.Decode.int)) (Json.Decode.index 1 (Json.Decode.string)))`

This isn't going to work since you can't call `(,)` anymore. There is a function called [pair](https://package.elm-lang.org/packages/elm/core/1.0.0/Tuple) that works for 2-tuples, but I'm not sure what to do for n-ary tuples yet.

I'll keep looking through the test output, and let you know what else I find.

**Comment by tmbull** [comment]
I created an ellie [here ](https://ellie-app.com/3jd3XGRJSWra1) where I just pasted in the Helpers code ahead of the output from:

````
  test\Elm\ModuleSpec.hs:117:
  1) makeElmModule should produce the correct code
```

The only line that didn't work was the tuple line I mentioned above, which I think can be solved by just replacing `(,)` with `pair` in this case. You might be able to get around this issue by adding a `triple` function to `json-helpers` that creates a 3-ary tuple. It seems that elm dropped support for tuples larger than 3 in 0.19 anyway, so that will need to be handled by `elm-bridge`.

**Comment by bartavelle** [comment]
You can just copy the `Json` directory into your code and drop the dependency to test the module.

**Comment by bartavelle** [comment]
I "kind of" fixed the tuple situation in both elm-bridge and json-helpers.

**Comment by tmbull** [comment]
I've been messing around with your tuple "fix" and it seems to work from my experience.

BTW, I also submitted a small PR [here ](https://github.com/agrafix/elm-bridge/pull/36) around the EndToEnd test (which passes now, btw).
